# Generated by Django 5.1.6 on 2025-03-11 17:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sattellite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sattelite_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RasterData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('raster', django.contrib.gis.db.models.fields.RasterField(help_text='Data raster GeoTIFF yang disimpan dalam PostGIS', srid=4326)),
                ('time_retrieve', models.DateField()),
                ('sattellite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raster_data', to='Aod_data.sattellite')),
            ],
        ),
    ]
