# Generated by Django 5.1.6 on 2025-05-02 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pm25DataEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuepm25', models.JSONField()),
                ('time', models.DateField()),
                ('aodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm25data_actual', to='Aod_data.rasterdata')),
            ],
        ),
    ]
