# Generated by Django 5.1.6 on 2025-05-02 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0002_pm25dataestimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm25dataestimate',
            name='aodid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm25data_estimate', to='Aod_data.rasterdata'),
        ),
    ]
