# Generated by Django 5.1.6 on 2025-05-16 03:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0004_pm25dataestimate_raster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasterdata',
            name='raster',
        ),
        migrations.AddField(
            model_name='rasterdata',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
