# Generated by Django 5.1.6 on 2025-05-16 04:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0005_remove_rasterdata_raster_rasterdata_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdata',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
