# Generated by Django 5.1.6 on 2025-05-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0006_alter_rasterdata_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterdata',
            name='aod_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
