# Generated by Django 5.1.6 on 2025-05-17 03:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0007_rasterdata_aod_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasterdata',
            name='aod_value',
        ),
        migrations.RemoveField(
            model_name='rasterdata',
            name='geom',
        ),
        migrations.CreateModel(
            name='Polygondata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('aod_value', models.FloatField()),
                ('date', models.DateField()),
                ('aodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aod_polygon', to='Aod_data.rasterdata')),
            ],
        ),
    ]
