# Generated by Django 5.1.6 on 2025-05-17 21:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0008_remove_rasterdata_aod_value_remove_rasterdata_geom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pm25dataestimate',
            name='raster',
        ),
        migrations.CreateModel(
            name='PolygondataPM25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('aod_value', models.FloatField()),
                ('date', models.DateField()),
                ('pm25id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm25_polygon', to='Aod_data.rasterdata')),
            ],
        ),
    ]
