# Generated by Django 5.1.6 on 2025-05-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0009_remove_pm25dataestimate_raster_polygondatapm25'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygondatapm25',
            old_name='aod_value',
            new_name='pm25_value',
        ),
    ]
