# Generated by Django 5.1.6 on 2025-05-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aod_data', '0010_rename_aod_value_polygondatapm25_pm25_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygondatapm25',
            name='pm25id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm25_polygon', to='Aod_data.pm25dataestimate'),
        ),
    ]
