# Generated by Django 5.1.6 on 2025-05-01 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pm25DataActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25_value', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm25data_actual', to='Weather_data.weatherstation')),
            ],
        ),
        migrations.CreateModel(
            name='pm25DataPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pm25_value', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm25data_prediction', to='Weather_data.weatherstation')),
            ],
        ),
    ]
