# Generated by Django 5.1.6 on 2025-05-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_data', '0002_pm25dataactual_pm25dataprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
