# Generated by Django 5.1.6 on 2025-05-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_data', '0003_alter_weatherdata_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='timestamp',
            new_name='date',
        ),
    ]
