# Generated by Django 5.1.6 on 2025-05-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_data', '0004_rename_timestamp_weatherdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm25dataactual',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
