# Generated by Django 5.1.6 on 2025-05-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_data', '0006_weatherdata_cloud_cover_weatherdata_dew_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='precip_cover',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='sea_level_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='solar_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='solar_radiation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='visibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_dir',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
