# Generated by Django 5.1.6 on 2025-05-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_data', '0007_weatherdata_precip_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm25dataactual',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
