# Generated by Django 5.1.6 on 2025-05-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weather_data', '0008_alter_pm25dataactual_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pm25dataactual',
            old_name='datetime',
            new_name='date',
        ),
    ]
